name: Deploy on S3
on:
  push:
    branches:
      - test

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          
      - name: Build
        continue-on-error: true
        run: |
          export REACT_APP_LAUNCHDARKLY_ACCESS_TOKEN=test
          yarn install && yarn build
          
      - run: ls -lah build/
