name: Deploy on S3
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          
      - name: Build
        continue-on-error: true
        run: |
          export REACT_APP_LAUNCHDARKLY_ACCESS_TOKEN=${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
          yarn install && yarn build
          
      - name: Push code to S3
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=us-east-1
          aws s3 cp build/ s3://hackerrank-dev-launchdarkly --recursive
