name: Deploy on S3
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          
      - name: Build
        continue-on-error: true
        run: |
          export REACT_APP_LAUNCHDARKLY_ACCESS_TOKEN=${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
          yarn install && yarn build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          
      - name: Push code to S3
        run:  aws s3 cp build/ s3://hackerrank-dev-launchdarkly --recursive
