name: Deploy on S3
on:
  push:
    branches:
      - test

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          
      - name: Build
        continue-on-error: true
        run: |
          export REACT_APP_LAUNCHDARKLY_ACCESS_TOKEN=test
          yarn install && yarn build
          
      - run: ls -lah build/
      
      - name: Push Code to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_DEV_ACCESS_KEY}}
          aws_secret_access_key: ${{secrets.AWS_DEV_SECRET_ACCESS_KEY}}
          aws_bucket: hackerrank-dev-launchdarkly
          source_dir: build/
